// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package vearch provides testctr support for vearch containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: vearch/vearch:latest
  - Port: 9001
  - Wait Strategy: "ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/vearch"
	)

	func TestWithVearch(t *testing.T) {
		container := testctr.New(t, "vearch/vearch:latest", vearch.Default())
		// Use container...
	}


*/
package vearch
