// Code generated by generate-all-modules. DO NOT EDIT.

package cockroachdb

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for cockroachdb containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("26257"),
		ctropts.WithWaitForLog("CockroachDB node starting", 30*time.Second),
		// TODO: Add DSN provider when fully implemented
	)
}
