// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package cockroachdb provides testctr support for cockroachdb containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: cockroachdb/cockroach:v23.1.0
  - Port: 26257
  - Wait Strategy: "CockroachDB node starting"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/cockroachdb"
	)

	func TestWithCockroachdb(t *testing.T) {
		container := testctr.New(t, "cockroachdb/cockroach:v23.1.0", cockroachdb.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

*/
package cockroachdb
