// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package nats provides testctr support for nats containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: nats:latest
  - Port: 4222
  - Wait Strategy: "Server is ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/nats"
	)

	func TestWithNats(t *testing.T) {
		container := testctr.New(t, "nats:latest", nats.Default())
		// Use container...
	}


*/
package nats
