// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package dockermodelrunner provides testctr support for dockermodelrunner containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: testcontainers/ryuk:0.5.1
  - Port: 8080
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/dockermodelrunner"
	)

	func TestWithDockermodelrunner(t *testing.T) {
		container := testctr.New(t, "testcontainers/ryuk:0.5.1", dockermodelrunner.Default())
		// Use container...
	}


*/
package dockermodelrunner
