// Code generated by generate-all-modules. DO NOT EDIT.

package clickhouse

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for clickhouse containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("9000"),
		ctropts.WithWaitForLog("Ready for connections", 30*time.Second),
		// TODO: Add DSN provider when fully implemented
	)
}
