// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package clickhouse provides testctr support for clickhouse containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: clickhouse/clickhouse-server:23
  - Port: 9000
  - Wait Strategy: "Ready for connections"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/clickhouse"
	)

	func TestWithClickhouse(t *testing.T) {
		container := testctr.New(t, "clickhouse/clickhouse-server:23", clickhouse.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

*/
package clickhouse
