#!/usr/bin/env bash
# finalize.sh — publish the final standalone manpage and a companion
# txtar bundle after a design run completes.
#
# A Plan 9 design IS a synthetic filesystem, so the canonical artifact
# is two-part:
#
#   1. <service>(4).md   — the standalone manual-page document
#   2. <service>.txtar    — a txtar archive that, when extracted, yields
#                           a directory tree containing:
#                             <service>(4).md       (the manpage)
#                             tree.txt              (just § 2's ASCII tree)
#                             examples/NN-NAME.rc   (each § 5 worked example
#                                                    as a runnable rc script)
#                             schema/NAME.json      (inline JSON schemas
#                                                    referenced in § 3)
#                             README.md             (orientation)
#
# Both are written to two canonical locations:
#   $WORK/<service>(4).md and $WORK/<service>.txtar
#   $PLAN9_FS_CATALOG/<service>(4).md and .../<service>/   (extracted)
#
# Defaults: PLAN9_FS_CATALOG=~/plan9-fs-specs
#
# Idempotent; safe to re-run.
#
# Usage:
#   finalize.sh <slug>

set -euo pipefail

if [ "$#" -lt 1 ]; then
    echo "usage: finalize.sh <slug>" >&2
    exit 2
fi

SLUG="$1"
PLAN9_FS_HOME="${PLAN9_FS_HOME:-$HOME/.plan9-fs-designs}"
WORK="$PLAN9_FS_HOME/$SLUG"
CATALOG="${PLAN9_FS_CATALOG:-$HOME/plan9-fs-specs}"

[ -d "$WORK" ] || { echo "no work dir for $SLUG" >&2; exit 1; }

# Source document — bundle.sh writes out/<slug>(4).md; fall back to
# probes/09 if bundle hasn't been run yet.
SRC="$WORK/out/${SLUG}(4).md"
[ -f "$SRC" ] || SRC="$WORK/probes/09-synthesize-document.md"
[ -f "$SRC" ] || { echo "no document at $WORK/out or probes/09" >&2; exit 1; }

# Derive <service> from the H1 ("# prompt(4) — ..."). Falls back to slug.
SERVICE=$(awk '/^# .*\([0-9]+\)/ { match($0, /[A-Za-z][A-Za-z0-9_-]*\(/); if (RSTART>0) { s=substr($0, RSTART, RLENGTH-1); print s; exit } }' "$SRC")
[ -n "$SERVICE" ] || SERVICE="$SLUG"

mkdir -p "$CATALOG"

# ---------------------------------------------------------------------
# Step 1: standalone <service>(4).md with provenance header.
# ---------------------------------------------------------------------

WORK_MANPAGE="$WORK/${SERVICE}(4).md"
CATALOG_MANPAGE="$CATALOG/${SERVICE}(4).md"

NB_ID=""
NB_CACHE="$PLAN9_FS_HOME/.notebook-id"
[ -f "$NB_CACHE" ] && NB_ID=$(cat "$NB_CACHE")

CONV_ID=""
[ -f "$WORK/conv-id.txt" ] && CONV_ID=$(cat "$WORK/conv-id.txt")

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SKILL_SHA=""
if git -C "$SKILL_DIR" rev-parse --short HEAD >/dev/null 2>&1; then
    SKILL_SHA=$(git -C "$SKILL_DIR" rev-parse --short HEAD)
fi

{
    echo "<!--"
    echo "  generated by /plan9-fs-api-design"
    echo "  slug:        $SLUG"
    [ -n "$CONV_ID" ] && echo "  conv-id:     $CONV_ID"
    [ -n "$NB_ID" ]   && echo "  notebook:    $NB_ID"
    echo "  generated:   $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    [ -n "$SKILL_SHA" ] && echo "  skill-sha:   $SKILL_SHA"
    echo "-->"
    echo ""
    cat "$SRC"
} > "$WORK_MANPAGE"

cp "$WORK_MANPAGE" "$CATALOG_MANPAGE"
echo "wrote: $WORK_MANPAGE" >&2
echo "wrote: $CATALOG_MANPAGE" >&2

# ---------------------------------------------------------------------
# Step 2: assemble a txtar bundle from the manpage + extracted artifacts.
# We do NOT trust the model to emit valid txtar; we build it locally.
# ---------------------------------------------------------------------

STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT

# 2a. Manpage at archive root.
cp "$WORK_MANPAGE" "$STAGE/${SERVICE}(4).md"

# 2b. tree.txt — extract the first fenced block under "### 2. Filesystem tree".
awk '
    /^### 2\. /              { in2=1; next }
    in2 && /^### /            { in2=0 }
    in2 && /^```/             { fence = !fence; next }
    in2 && fence              { print }
' "$WORK_MANPAGE" > "$STAGE/tree.txt"
[ -s "$STAGE/tree.txt" ] || rm -f "$STAGE/tree.txt"

# 2c. examples/NN-NAME.rc — each fenced sh/rc block under § 5.
mkdir -p "$STAGE/examples"
awk -v outdir="$STAGE/examples" '
    /^### 5\. /                       { in5=1; n=0; next }
    in5 && /^### /                    { in5=0 }
    in5 && /^\*\*[0-9]+\./             { n++; title=$0; gsub(/^\*\*[0-9]+\. /,"",title); gsub(/\*\*$/,"",title); gsub(/[^A-Za-z0-9]+/,"-",title); gsub(/^-+|-+$/,"",title); next }
    in5 && /^#### /                    { n++; title=$0; gsub(/^#### /,"",title); gsub(/[^A-Za-z0-9]+/,"-",title); gsub(/^-+|-+$/,"",title); next }
    in5 && /^```/                     {
        if (!fence && n>0) {
            fname=sprintf("%s/%02d-%s.rc", outdir, n, tolower(title))
            f=fname
            fence=1
            next
        } else if (fence) {
            fence=0
            close(f)
            f=""
            next
        }
    }
    in5 && fence && f                 { print > f }
' "$WORK_MANPAGE"
# Drop the examples dir if empty.
rmdir "$STAGE/examples" 2>/dev/null || true

# 2d. schema/NAME.json — any fenced ```json block under § 3 paired with
# an immediately preceding /<path>/ heading whose path contains "constraint"
# or "schema". Heuristic; only fires if probe 05 happens to inline JSON.
mkdir -p "$STAGE/schema"
awk -v outdir="$STAGE/schema" '
    /^#### `\// {
        line=$0
        gsub(/^.*\//, "", line)
        gsub(/`.*/, "", line)
        gsub(/[^A-Za-z0-9_-]/, "", line)
        if (length(line) > 0) current=line
        next
    }
    /^```json/ && current  { fence=1; f=outdir "/" current ".json"; next }
    fence && /^```/        { fence=0; close(f); f=""; current=""; next }
    fence && f             { print > f }
' "$WORK_MANPAGE"
rmdir "$STAGE/schema" 2>/dev/null || true

# 2e. README.md orienting the user.
cat > "$STAGE/README.md" <<EOF
# ${SERVICE}(4) — extracted design bundle

This directory was extracted from \`${SERVICE}.txtar\` produced by
\`/plan9-fs-api-design\`.

- \`${SERVICE}(4).md\` — the manual-page-style design document. Read this first.
- \`tree.txt\` — just the filesystem tree (§ 2 of the manpage), copy-pasteable.
- \`examples/\` — each worked end-to-end example from § 5 as a runnable rc script.
- \`schema/\` — JSON schemas referenced inline in § 3 (if any).

Provenance is in the HTML comment block at the top of the manpage.
EOF

# 2f. Assemble into a txtar archive.
WORK_TXTAR="$WORK/${SERVICE}.txtar"
CATALOG_DIR="$CATALOG/${SERVICE}"

(cd "$STAGE" && printf 'generated by /plan9-fs-api-design\n' | txtar . > "$WORK_TXTAR")
echo "wrote: $WORK_TXTAR" >&2

# 2g. Also extract a copy under the catalog directory so the user has
# a browsable per-design tree without needing to txtar -x manually.
rm -rf "$CATALOG_DIR"
mkdir -p "$CATALOG_DIR"
(cd "$CATALOG_DIR" && txtar -x < "$WORK_TXTAR")
echo "wrote: $CATALOG_DIR/" >&2

echo "$CATALOG_MANPAGE"
