// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package gcloud provides testctr support for gcloud containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  - Port: 8080
  - Wait Strategy: "ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/gcloud"
	)

	func TestWithGcloud(t *testing.T) {
		container := testctr.New(t, "gcr.io/google.com/cloudsdktool/cloud-sdk:latest", gcloud.Default())
		// Use container...
	}


*/
package gcloud
