// Code generated by generate-all-modules. DO NOT EDIT.

package gcloud

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for gcloud containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8080"),
		ctropts.WithWaitForLog("ready", 30*time.Second),
	)
}
