// Code generated by generate-all-modules. DO NOT EDIT.

package influxdb

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for influxdb containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8086"),
		ctropts.WithWaitForLog("started", 30*time.Second),
	)
}
