// Code generated by generate-all-modules. DO NOT EDIT.

package modules_test

import (
	"testing"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/exp/modules/aerospike"
	"github.com/tmc/misc/testctr/exp/modules/arangodb"
	"github.com/tmc/misc/testctr/exp/modules/artemis"
	"github.com/tmc/misc/testctr/exp/modules/azure"
	"github.com/tmc/misc/testctr/exp/modules/azurite"
	"github.com/tmc/misc/testctr/exp/modules/cassandra"
	"github.com/tmc/misc/testctr/exp/modules/chroma"
	"github.com/tmc/misc/testctr/exp/modules/clickhouse"
	"github.com/tmc/misc/testctr/exp/modules/cockroachdb"
	"github.com/tmc/misc/testctr/exp/modules/consul"
	"github.com/tmc/misc/testctr/exp/modules/couchbase"
	"github.com/tmc/misc/testctr/exp/modules/databend"
	"github.com/tmc/misc/testctr/exp/modules/dind"
	"github.com/tmc/misc/testctr/exp/modules/dockermodelrunner"
	"github.com/tmc/misc/testctr/exp/modules/dolt"
	"github.com/tmc/misc/testctr/exp/modules/dynamodb"
	"github.com/tmc/misc/testctr/exp/modules/elasticsearch"
	"github.com/tmc/misc/testctr/exp/modules/etcd"
	"github.com/tmc/misc/testctr/exp/modules/gcloud"
	"github.com/tmc/misc/testctr/exp/modules/inbucket"
	"github.com/tmc/misc/testctr/exp/modules/influxdb"
	"github.com/tmc/misc/testctr/exp/modules/k3s"
	"github.com/tmc/misc/testctr/exp/modules/k6"
	"github.com/tmc/misc/testctr/exp/modules/kafka"
	"github.com/tmc/misc/testctr/exp/modules/localstack"
	"github.com/tmc/misc/testctr/exp/modules/mariadb"
	"github.com/tmc/misc/testctr/exp/modules/meilisearch"
	"github.com/tmc/misc/testctr/exp/modules/memcached"
	"github.com/tmc/misc/testctr/exp/modules/milvus"
	"github.com/tmc/misc/testctr/exp/modules/minio"
	"github.com/tmc/misc/testctr/exp/modules/mockserver"
	"github.com/tmc/misc/testctr/exp/modules/mongodb"
	"github.com/tmc/misc/testctr/exp/modules/mssql"
	"github.com/tmc/misc/testctr/exp/modules/mysql"
	"github.com/tmc/misc/testctr/exp/modules/nats"
	"github.com/tmc/misc/testctr/exp/modules/neo4j"
	"github.com/tmc/misc/testctr/exp/modules/ollama"
	"github.com/tmc/misc/testctr/exp/modules/openfga"
	"github.com/tmc/misc/testctr/exp/modules/openldap"
	"github.com/tmc/misc/testctr/exp/modules/opensearch"
	"github.com/tmc/misc/testctr/exp/modules/pinecone"
	"github.com/tmc/misc/testctr/exp/modules/postgres"
	"github.com/tmc/misc/testctr/exp/modules/pulsar"
	"github.com/tmc/misc/testctr/exp/modules/qdrant"
	"github.com/tmc/misc/testctr/exp/modules/rabbitmq"
	"github.com/tmc/misc/testctr/exp/modules/redis"
	"github.com/tmc/misc/testctr/exp/modules/redpanda"
	"github.com/tmc/misc/testctr/exp/modules/registry"
	"github.com/tmc/misc/testctr/exp/modules/scylladb"
	"github.com/tmc/misc/testctr/exp/modules/socat"
	"github.com/tmc/misc/testctr/exp/modules/surrealdb"
	"github.com/tmc/misc/testctr/exp/modules/toxiproxy"
	"github.com/tmc/misc/testctr/exp/modules/valkey"
	"github.com/tmc/misc/testctr/exp/modules/vault"
	"github.com/tmc/misc/testctr/exp/modules/vearch"
	"github.com/tmc/misc/testctr/exp/modules/weaviate"
	"github.com/tmc/misc/testctr/exp/modules/yugabytedb"
)

func TestAllGeneratedModules(t *testing.T) {
	t.Run("chroma", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "chromadb/chroma:latest", chroma.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("chroma container running on port %s", port)
	})

	t.Run("milvus", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "milvusdb/milvus:latest", milvus.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("milvus container running on port %s", port)
	})

	t.Run("mongodb", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "mongo:7", mongodb.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("mongodb container running on port %s", port)
	})

	t.Run("mysql", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "mysql:8", mysql.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("mysql container running on port %s", port)
	})

	t.Run("ollama", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "ollama/ollama:latest", ollama.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("ollama container running on port %s", port)
	})

	t.Run("qdrant", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "qdrant/qdrant:latest", qdrant.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("qdrant container running on port %s", port)
	})

	t.Run("redis", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "redis:7", redis.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("redis container running on port %s", port)
	})

	t.Run("opensearch", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "opensearchproject/opensearch:2", opensearch.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("opensearch container running on port %s", port)
	})

	t.Run("postgres", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "postgres:15", postgres.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("postgres container running on port %s", port)
	})

	t.Run("weaviate", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "semitechnologies/weaviate:latest", weaviate.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("weaviate container running on port %s", port)
	})

	t.Run("aerospike", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "aerospike:ce-6.4.0.1", aerospike.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("aerospike container running on port %s", port)
	})

	t.Run("arangodb", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "arangodb:3.11", arangodb.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("arangodb container running on port %s", port)
	})

	t.Run("artemis", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "artemis:latest", artemis.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("artemis container running on port %s", port)
	})

	t.Run("azure", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "azure:latest", azure.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("azure container running on port %s", port)
	})

	t.Run("azurite", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "mcr.microsoft.com/azure-storage/azurite:latest", azurite.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("azurite container running on port %s", port)
	})

	t.Run("cassandra", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "cassandra:4", cassandra.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("cassandra container running on port %s", port)
	})

	t.Run("clickhouse", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "clickhouse/clickhouse-server:23", clickhouse.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("clickhouse container running on port %s", port)
	})

	t.Run("cockroachdb", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "cockroachdb/cockroach:v23.1.0", cockroachdb.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("cockroachdb container running on port %s", port)
	})

	t.Run("consul", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "hashicorp/consul:1.15", consul.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("consul container running on port %s", port)
	})

	t.Run("couchbase", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "couchbase:7", couchbase.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("couchbase container running on port %s", port)
	})

	t.Run("databend", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "datafuselabs/databend:v1.0.0", databend.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("databend container running on port %s", port)
	})

	t.Run("dind", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "docker:dind", dind.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("dind container running on port %s", port)
	})

	t.Run("dockermodelrunner", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "testcontainers/ryuk:0.5.1", dockermodelrunner.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("dockermodelrunner container running on port %s", port)
	})

	t.Run("dolt", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "dolthub/dolt-sql-server:latest", dolt.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("dolt container running on port %s", port)
	})

	t.Run("dynamodb", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "amazon/dynamodb-local:latest", dynamodb.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("dynamodb container running on port %s", port)
	})

	t.Run("elasticsearch", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "docker.elastic.co/elasticsearch/elasticsearch:8.9.0", elasticsearch.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("elasticsearch container running on port %s", port)
	})

	t.Run("etcd", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "quay.io/coreos/etcd:v3.5.9", etcd.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("etcd container running on port %s", port)
	})

	t.Run("gcloud", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "gcr.io/google.com/cloudsdktool/cloud-sdk:latest", gcloud.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("gcloud container running on port %s", port)
	})

	t.Run("inbucket", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "inbucket/inbucket:latest", inbucket.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("inbucket container running on port %s", port)
	})

	t.Run("influxdb", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "influxdb:2.7", influxdb.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("influxdb container running on port %s", port)
	})

	t.Run("k3s", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "rancher/k3s:v1.27.3-k3s1", k3s.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("k3s container running on port %s", port)
	})

	t.Run("k6", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "grafana/k6:0.45.0", k6.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("k6 container running on port %s", port)
	})

	t.Run("kafka", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "confluentinc/cp-kafka:7.5.0", kafka.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("kafka container running on port %s", port)
	})

	t.Run("localstack", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "localstack/localstack:3.0", localstack.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("localstack container running on port %s", port)
	})

	t.Run("mariadb", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "mariadb:10", mariadb.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("mariadb container running on port %s", port)
	})

	t.Run("meilisearch", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "getmeili/meilisearch:v1.3", meilisearch.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("meilisearch container running on port %s", port)
	})

	t.Run("memcached", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "memcached:alpine", memcached.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("memcached container running on port %s", port)
	})

	t.Run("minio", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "minio/minio:latest", minio.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("minio container running on port %s", port)
	})

	t.Run("mockserver", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "mockserver/mockserver:5.15.0", mockserver.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("mockserver container running on port %s", port)
	})

	t.Run("mssql", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "mcr.microsoft.com/mssql/server:2022-latest", mssql.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("mssql container running on port %s", port)
	})

	t.Run("nats", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "nats:latest", nats.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("nats container running on port %s", port)
	})

	t.Run("neo4j", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "neo4j:5", neo4j.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("neo4j container running on port %s", port)
	})

	t.Run("openfga", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "openfga/openfga:v1.3.0", openfga.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("openfga container running on port %s", port)
	})

	t.Run("openldap", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "osixia/openldap:1.5.0", openldap.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("openldap container running on port %s", port)
	})

	t.Run("pinecone", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "pinecone:latest", pinecone.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("pinecone container running on port %s", port)
	})

	t.Run("pulsar", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "apachepulsar/pulsar:3.1.0", pulsar.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("pulsar container running on port %s", port)
	})

	t.Run("rabbitmq", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "rabbitmq:3-management", rabbitmq.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("rabbitmq container running on port %s", port)
	})

	t.Run("redpanda", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "redpandadata/redpanda:v23.2.3", redpanda.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("redpanda container running on port %s", port)
	})

	t.Run("registry", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "registry:2", registry.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("registry container running on port %s", port)
	})

	t.Run("scylladb", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "scylladb/scylla:5.2", scylladb.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("scylladb container running on port %s", port)
	})

	t.Run("socat", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "alpine/socat:latest", socat.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("socat container running on port %s", port)
	})

	t.Run("surrealdb", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "surrealdb/surrealdb:v1.0.0", surrealdb.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("surrealdb container running on port %s", port)
	})

	t.Run("toxiproxy", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "ghcr.io/shopify/toxiproxy:2.5.0", toxiproxy.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("toxiproxy container running on port %s", port)
	})

	t.Run("valkey", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "valkey/valkey:7.2", valkey.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("valkey container running on port %s", port)
	})

	t.Run("vault", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "hashicorp/vault:1.15", vault.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("vault container running on port %s", port)
	})

	t.Run("vearch", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "vearch/vearch:latest", vearch.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("vearch container running on port %s", port)
	})

	t.Run("yugabytedb", func(t *testing.T) {
		t.Parallel()

		container := testctr.New(t, "yugabytedb/yugabyte:2.18.0.0-b80", yugabytedb.Default())

		if container.ID() == "" {
			t.Fatal("container ID should not be empty")
		}

		port := container.Port()
		if port == "" {
			t.Fatal("container port should not be empty")
		}

		t.Logf("yugabytedb container running on port %s", port)
	})

}
