// Code generated by generate-all-modules. DO NOT EDIT.

package mariadb

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for mariadb containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("3306"),
		ctropts.WithWaitForLog("ready for connections", 30*time.Second),
		// TODO: Add DSN provider when fully implemented
	)
}
