// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package pulsar provides testctr support for pulsar containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: apachepulsar/pulsar:3.1.0
  - Port: 6650
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/pulsar"
	)

	func TestWithPulsar(t *testing.T) {
		container := testctr.New(t, "apachepulsar/pulsar:3.1.0", pulsar.Default())
		// Use container...
	}


*/
package pulsar
