// Code generated by generate-all-modules. DO NOT EDIT.

package databend

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for databend containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8000"),
		ctropts.WithWaitForLog("Databend HTTP server listening", 30*time.Second),
		// TODO: Add DSN provider when fully implemented
	)
}
