// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package weaviate provides testctr support for weaviate containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: semitechnologies/weaviate:latest
  - Port: 50051/tcp
  - Wait Strategy: "ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/weaviate"
	)

	func TestWithWeaviate(t *testing.T) {
		container := testctr.New(t, "semitechnologies/weaviate:latest", weaviate.Default())
		// Use container...
	}


*/
package weaviate
