// Code generated by generate-all-modules. DO NOT EDIT.

package chroma

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for chroma containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8000"),
		ctropts.WithWaitForLog("ready", 30*time.Second),
	)
}
