// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package chroma provides testctr support for chroma containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: chromadb/chroma:latest
  - Port: 8000
  - Wait Strategy: "ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/chroma"
	)

	func TestWithChroma(t *testing.T) {
		container := testctr.New(t, "chromadb/chroma:latest", chroma.Default())
		// Use container...
	}


*/
package chroma
