// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package milvus provides testctr support for milvus containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: milvusdb/milvus:latest
  - Port: 19530/tcp
  - Wait Strategy: "ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/milvus"
	)

	func TestWithMilvus(t *testing.T) {
		container := testctr.New(t, "milvusdb/milvus:latest", milvus.Default())
		// Use container...
	}


*/
package milvus
