// Code generated by generate-all-modules. DO NOT EDIT.

package milvus

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for milvus containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("19530/tcp"),
		ctropts.WithWaitForLog("ready", 30*time.Second),
	)
}
