// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package scylladb provides testctr support for scylladb containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: scylladb/scylla:5.2
  - Port: 9042
  - Wait Strategy: "Started ScyllaDB"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/scylladb"
	)

	func TestWithScylladb(t *testing.T) {
		container := testctr.New(t, "scylladb/scylla:5.2", scylladb.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

*/
package scylladb
