// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package ollama provides testctr support for ollama containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: ollama/ollama:latest
  - Port: 11434/tcp
  - Wait Strategy: "Ollama is running"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/ollama"
	)

	func TestWithOllama(t *testing.T) {
		container := testctr.New(t, "ollama/ollama:latest", ollama.Default())
		// Use container...
	}


# Configuration Options

  - WithUseLocal: WithUseLocal starts a local Ollama process with the given environment in format KEY=VALUE instead of a Docker container, which can be more performant as it has direct access to the GPU. By default `OLLAMA_HOST=localhost:0` is set to avoid port conflicts. When using this option, the container request will be validated to ensure that only the options that are compatible with the local process are used. Supported fields are: - [testcontainers.GenericContainerRequest.Started] must be set to true - [testcontainers.GenericContainerRequest.ExposedPorts] must be set to ["11434/tcp"] - [testcontainers.ContainerRequest.WaitingFor] should not be changed from the default - [testcontainers.ContainerRequest.Image] used to determine the local process binary [<path-ignored>/]<binary>[:latest] if not blank. - [testcontainers.ContainerRequest.Env] applied to all local process executions - [testcontainers.GenericContainerRequest.Logger] is unused Any other leaf field not set to the type's zero value will result in an error.
*/
package ollama
