// Code generated by generate-all-modules. DO NOT EDIT.

package ollama

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for ollama containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("11434/tcp"),
		ctropts.WithWaitForLog("Ollama is running", 30*time.Second),
	)
}

// WithUseLocal WithUseLocal starts a local Ollama process with the given environment in format KEY=VALUE instead of a Docker container, which can be more performant as it has direct access to the GPU. By default `OLLAMA_HOST=localhost:0` is set to avoid port conflicts. When using this option, the container request will be validated to ensure that only the options that are compatible with the local process are used. Supported fields are: - [testcontainers.GenericContainerRequest.Started] must be set to true - [testcontainers.GenericContainerRequest.ExposedPorts] must be set to ["11434/tcp"] - [testcontainers.ContainerRequest.WaitingFor] should not be changed from the default - [testcontainers.ContainerRequest.Image] used to determine the local process binary [<path-ignored>/]<binary>[:latest] if not blank. - [testcontainers.ContainerRequest.Env] applied to all local process executions - [testcontainers.GenericContainerRequest.Logger] is unused Any other leaf field not set to the type's zero value will result in an error.
func WithUseLocal(value string) testctr.Option {
	return testctr.WithEnv("OLLAMA_USELOCAL", value)
}
