// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package surrealdb provides testctr support for surrealdb containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: surrealdb/surrealdb:v1.0.0
  - Port: 8000
  - Wait Strategy: "Started SurrealDB"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/surrealdb"
	)

	func TestWithSurrealdb(t *testing.T) {
		container := testctr.New(t, "surrealdb/surrealdb:v1.0.0", surrealdb.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

*/
package surrealdb
