// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package mssql provides testctr support for mssql containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: mcr.microsoft.com/mssql/server:2022-latest
  - Port: 1433
  - Wait Strategy: "SQL Server is now ready for client connections"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/mssql"
	)

	func TestWithMssql(t *testing.T) {
		container := testctr.New(t, "mcr.microsoft.com/mssql/server:2022-latest", mssql.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

*/
package mssql
