// Code generated by generate-all-modules. DO NOT EDIT.

package mssql

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for mssql containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("1433"),
		ctropts.WithWaitForLog("SQL Server is now ready for client connections", 30*time.Second),
		// TODO: Add DSN provider when fully implemented
	)
}
