// Code generated by generate-all-modules. DO NOT EDIT.

package k6

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for k6 containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("6565"),
		ctropts.WithWaitForLog("k6 archive server running", 30*time.Second),
	)
}
