// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package mongodb provides testctr support for mongodb containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: mongo:7
  - Port: 27017
  - Wait Strategy: "waiting for connections"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/mongodb"
	)

	func TestWithMongodb(t *testing.T) {
		container := testctr.New(t, "mongo:7", mongodb.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

# Configuration Options

  - WithUsername: WithUsername sets the initial username to be created when the container starts It is used in conjunction with WithPassword to set a username and its password. It will create the specified user with superuser power.
  - WithPassword: WithPassword sets the initial password of the user to be created when the container starts It is used in conjunction with WithUsername to set a username and its password. It will set the superuser password for MongoDB.
  - WithReplicaSet: WithReplicaSet sets the replica set name for Single node MongoDB replica set.
*/
package mongodb
