// Code generated by generate-all-modules. DO NOT EDIT.

package mongodb

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for mongodb containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("27017"),
		ctropts.WithWaitForLog("waiting for connections", 30*time.Second),
		// TODO: Add DSN provider when fully implemented
	)
}

// WithUsername WithUsername sets the initial username to be created when the container starts It is used in conjunction with WithPassword to set a username and its password. It will create the specified user with superuser power.
func WithUsername(value string) testctr.Option {
	return testctr.WithEnv("MONGODB_USER", value)
}

// WithPassword WithPassword sets the initial password of the user to be created when the container starts It is used in conjunction with WithUsername to set a username and its password. It will set the superuser password for MongoDB.
func WithPassword(value string) testctr.Option {
	return testctr.WithEnv("MONGODB_PASSWORD", value)
}

// WithReplicaSet WithReplicaSet sets the replica set name for Single node MongoDB replica set.
func WithReplicaSet(value string) testctr.Option {
	return testctr.WithEnv("MONGODB_REPLICASET", value)
}
