// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package elasticsearch provides testctr support for elasticsearch containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
  - Port: 9200
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/elasticsearch"
	)

	func TestWithElasticsearch(t *testing.T) {
		container := testctr.New(t, "docker.elastic.co/elasticsearch/elasticsearch:8.9.0", elasticsearch.Default())
		// Use container...
	}


*/
package elasticsearch
