// Command protofrompy recovers .proto source files from generated Python
// protobuf code (*_pb2.py).
//
// Every file generated by the modern protobuf Python backend embeds a complete,
// serialized FileDescriptorProto in its AddSerializedFile(b'...') call. That
// descriptor carries the full schema — messages, enums, fields, types, oneofs,
// maps, nested types, options — so the original .proto can be reconstructed
// with high fidelity without the .proto source, protoc, or a running Python
// interpreter.
//
// protofrompy extracts that descriptor and renders it back to .proto text.
// Field/message/enum names, numbers, labels, types, oneofs, map entries,
// reserved ranges, and well-known options are recovered. What cannot be
// recovered are artifacts that the descriptor does not retain: comments,
// original field ordering vs. number ordering, custom option text, and exact
// whitespace.
//
// Usage:
//
//	protofrompy [flags] <file_or_dir>...
//
// Each argument is a _pb2.py file or a directory searched recursively for
// *_pb2.py. Recovered .proto files are written to -out (default: stdout for a
// single input, else a directory mirroring the descriptors' file names).
//
// Flags:
//
//	-out dir     write recovered .proto files under dir (default: print to stdout)
//	-raw dir     also dump the raw serialized FileDescriptorProto bytes per file
//	-json        print the FileDescriptorProto as JSON instead of .proto text
//	-v           verbose: report each file and recovered type counts on stderr
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/jhump/protoreflect/desc"
	"github.com/jhump/protoreflect/desc/protoprint"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "protofrompy:", err)
		os.Exit(1)
	}
}

func run() error {
	out := flag.String("out", "", "write recovered .proto files under this directory (default: stdout)")
	rawDir := flag.String("raw", "", "also dump raw serialized FileDescriptorProto bytes under this directory")
	asJSON := flag.Bool("json", false, "print FileDescriptorProto as JSON instead of .proto text")
	verbose := flag.Bool("v", false, "verbose: report progress to stderr")
	flag.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage: protofrompy [flags] <file_or_dir>...")
		fmt.Fprintln(os.Stderr, "\nRecovers .proto source from generated Python *_pb2.py files.")
		flag.PrintDefaults()
	}
	flag.Parse()
	if flag.NArg() == 0 {
		flag.Usage()
		return fmt.Errorf("no inputs")
	}

	files, err := gatherInputs(flag.Args())
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return fmt.Errorf("no *_pb2.py files found in inputs")
	}

	// Pass 1: extract every FileDescriptorProto so cross-file dependencies can
	// be resolved together (a Datum in one file may reference a Tensor in
	// another, or in the same file).
	descs := make([]*descriptorpb.FileDescriptorProto, 0, len(files))
	byName := map[string]*descriptorpb.FileDescriptorProto{}
	for _, f := range files {
		src, err := os.ReadFile(f)
		if err != nil {
			return fmt.Errorf("%s: %w", f, err)
		}
		raw, err := extractSerializedFile(string(src))
		if err != nil {
			if *verbose {
				fmt.Fprintf(os.Stderr, "skip %s: %v\n", f, err)
			}
			continue
		}
		fdp := &descriptorpb.FileDescriptorProto{}
		if err := proto.Unmarshal(raw, fdp); err != nil {
			return fmt.Errorf("%s: unmarshal descriptor: %w", f, err)
		}
		name := fdp.GetName()
		if name == "" {
			name = strings.TrimSuffix(filepath.Base(f), "_pb2.py") + ".proto"
			fdp.Name = proto.String(name)
		}
		if _, dup := byName[name]; dup {
			if *verbose {
				fmt.Fprintf(os.Stderr, "skip %s: duplicate descriptor for %s\n", f, name)
			}
			continue
		}
		descs = append(descs, fdp)
		byName[name] = fdp
		if *rawDir != "" {
			if err := writeFile(filepath.Join(*rawDir, name+".fdp.bin"), raw); err != nil {
				return err
			}
		}
		if *verbose {
			fmt.Fprintf(os.Stderr, "recovered %s from %s (%d msgs, %d enums, %d deps)\n",
				name, f, len(fdp.MessageType), len(fdp.EnumType), len(fdp.Dependency))
		}
	}
	if len(descs) == 0 {
		return fmt.Errorf("no descriptors recovered (no AddSerializedFile found?)")
	}

	if *asJSON {
		return emitJSON(descs, *out)
	}
	return emitProto(descs, byName, *out, *verbose)
}

// gatherInputs expands file/dir arguments into a sorted, de-duplicated list of
// *_pb2.py paths.
func gatherInputs(args []string) ([]string, error) {
	seen := map[string]bool{}
	var files []string
	add := func(p string) {
		if !seen[p] {
			seen[p] = true
			files = append(files, p)
		}
	}
	for _, a := range args {
		info, err := os.Stat(a)
		if err != nil {
			return nil, err
		}
		if info.IsDir() {
			err := filepath.WalkDir(a, func(p string, d os.DirEntry, err error) error {
				if err != nil {
					return err
				}
				if !d.IsDir() && strings.HasSuffix(p, "_pb2.py") {
					add(p)
				}
				return nil
			})
			if err != nil {
				return nil, err
			}
			continue
		}
		add(a)
	}
	sort.Strings(files)
	return files, nil
}

// emitProto resolves the descriptors (wiring up dependencies) and renders each
// to .proto text via protoprint.
func emitProto(descs []*descriptorpb.FileDescriptorProto, byName map[string]*descriptorpb.FileDescriptorProto, outDir string, verbose bool) error {
	resolved, err := resolveFiles(descs, byName)
	if err != nil {
		return err
	}
	for _, fd := range resolved {
		var sb strings.Builder
		if err := emitProtoText(fd, &sb); err != nil {
			return fmt.Errorf("print %s: %w", fd.GetName(), err)
		}
		text := sb.String()
		if outDir == "" {
			// stdout; separate multiple files with a header banner.
			if len(resolved) > 1 {
				fmt.Printf("// ===== %s =====\n", fd.GetName())
			}
			fmt.Print(text)
			if !strings.HasSuffix(text, "\n") {
				fmt.Println()
			}
			continue
		}
		dst := filepath.Join(outDir, fd.GetName())
		if err := writeFile(dst, []byte(text)); err != nil {
			return err
		}
		if verbose {
			fmt.Fprintf(os.Stderr, "wrote %s\n", dst)
		}
	}
	return nil
}

// emitProtoText renders one resolved file to .proto text. The printer sorts
// elements by kind then name for stable output; comments are not in the
// descriptor, so none are emitted.
func emitProtoText(fd *desc.FileDescriptor, w io.Writer) error {
	printer := &protoprint.Printer{SortElements: true}
	return printer.PrintProtoFile(fd, w)
}

func emitJSON(descs []*descriptorpb.FileDescriptorProto, outDir string) error {
	m := protojson.MarshalOptions{Multiline: true, Indent: "  "}
	for _, fdp := range descs {
		b, err := m.Marshal(fdp)
		if err != nil {
			return err
		}
		if outDir == "" {
			fmt.Printf("// ===== %s =====\n%s\n", fdp.GetName(), b)
			continue
		}
		if err := writeFile(filepath.Join(outDir, fdp.GetName()+".json"), b); err != nil {
			return err
		}
	}
	return nil
}

// resolveFiles builds desc.FileDescriptors, providing dependency files from the
// recovered set when available. Missing dependencies (e.g. well-known types not
// present in the inputs) are tolerated where possible by synthesizing empty
// placeholders so a partial recovery still prints.
func resolveFiles(descs []*descriptorpb.FileDescriptorProto, byName map[string]*descriptorpb.FileDescriptorProto) ([]*desc.FileDescriptor, error) {
	cache := map[string]*desc.FileDescriptor{}
	var out []*desc.FileDescriptor
	for _, fdp := range descs {
		fd, err := resolveOne(fdp, byName, cache, map[string]bool{})
		if err != nil {
			return nil, err
		}
		out = append(out, fd)
	}
	return out, nil
}

func resolveOne(fdp *descriptorpb.FileDescriptorProto, byName map[string]*descriptorpb.FileDescriptorProto, cache map[string]*desc.FileDescriptor, onStack map[string]bool) (*desc.FileDescriptor, error) {
	name := fdp.GetName()
	if fd, ok := cache[name]; ok {
		return fd, nil
	}
	if onStack[name] {
		return nil, fmt.Errorf("import cycle through %s", name)
	}
	onStack[name] = true
	defer delete(onStack, name)

	var deps []*desc.FileDescriptor
	for _, dep := range fdp.GetDependency() {
		depFDP, ok := byName[dep]
		if !ok {
			// Dependency not among our inputs. Try the protoreflect global
			// registry (covers descriptor.proto and other linked well-known
			// types); if unavailable, synthesize a stub so printing proceeds.
			if known := lookupKnownDep(dep); known != nil {
				deps = append(deps, known)
				continue
			}
			depFDP = stubFile(dep)
			byName[dep] = depFDP
		}
		depFD, err := resolveOne(depFDP, byName, cache, onStack)
		if err != nil {
			return nil, err
		}
		deps = append(deps, depFD)
	}
	fd, err := desc.CreateFileDescriptor(fdp, deps...)
	if err != nil {
		return nil, fmt.Errorf("resolve %s: %w", name, err)
	}
	cache[name] = fd
	return fd, nil
}

func stubFile(name string) *descriptorpb.FileDescriptorProto {
	return &descriptorpb.FileDescriptorProto{
		Name:   proto.String(name),
		Syntax: proto.String("proto3"),
	}
}

func writeFile(path string, data []byte) error {
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	return os.WriteFile(path, data, 0o644)
}
