// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package etcd provides testctr support for etcd containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: quay.io/coreos/etcd:v3.5.9
  - Port: 2379
  - Wait Strategy: "ready to serve client requests"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/etcd"
	)

	func TestWithEtcd(t *testing.T) {
		container := testctr.New(t, "quay.io/coreos/etcd:v3.5.9", etcd.Default())
		// Use container...
	}


*/
package etcd
