// Code generated by generate-all-modules. DO NOT EDIT.

package etcd

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for etcd containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("2379"),
		ctropts.WithWaitForLog("ready to serve client requests", 30*time.Second),
	)
}
