// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package registry provides testctr support for registry containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: registry:2
  - Port: 5000
  - Wait Strategy: "listening on"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/registry"
	)

	func TestWithRegistry(t *testing.T) {
		container := testctr.New(t, "registry:2", registry.Default())
		// Use container...
	}


*/
package registry
