// Code generated by generate-all-modules. DO NOT EDIT.

package registry

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for registry containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("5000"),
		ctropts.WithWaitForLog("listening on", 30*time.Second),
	)
}
