// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package memcached provides testctr support for memcached containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: memcached:alpine
  - Port: 11211
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/memcached"
	)

	func TestWithMemcached(t *testing.T) {
		container := testctr.New(t, "memcached:alpine", memcached.Default())
		// Use container...
	}


*/
package memcached
