// Code generated by generate-all-modules. DO NOT EDIT.

package azure

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for azure containers.
func Default() testctr.Option {
	return testctr.Options(
		ctropts.WithWaitForLog("started", 30*time.Second),
	)
}
