// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package azure provides testctr support for azure containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: azure:latest
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/azure"
	)

	func TestWithAzure(t *testing.T) {
		container := testctr.New(t, "azure:latest", azure.Default())
		// Use container...
	}


*/
package azure
