// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package mysql provides testctr support for mysql containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: mysql:8
  - Port: 3306
  - Wait Strategy: "ready for connections"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/mysql"
	)

	func TestWithMysql(t *testing.T) {
		container := testctr.New(t, "mysql:8", mysql.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

# Configuration Options

  - WithDefaultCredentials: 
  - WithUsername: 
  - WithPassword: 
  - WithDatabase: 
  - WithConfigFile: 
  - WithScripts: 
*/
package mysql
