// Code generated by generate-all-modules. DO NOT EDIT.

package mysql

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for mysql containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("3306"),
		ctropts.WithWaitForLog("ready for connections", 30*time.Second),
		// TODO: Add DSN provider when fully implemented
	)
}

func WithDefaultCredentials(value string) testctr.Option {
	return testctr.WithEnv("MYSQL_DEFAULTCREDENTIALS", value)
}

func WithUsername(value string) testctr.Option {
	return testctr.WithEnv("MYSQL_USER", value)
}

func WithPassword(value string) testctr.Option {
	return testctr.WithEnv("MYSQL_PASSWORD", value)
}

func WithDatabase(value string) testctr.Option {
	return testctr.WithEnv("MYSQL_DATABASE", value)
}

func WithConfigFile(value string) testctr.Option {
	return testctr.WithEnv("MYSQL_CONFIGFILE", value)
}

func WithScripts(value string) testctr.Option {
	return testctr.WithEnv("MYSQL_SCRIPTS", value)
}
