// Code generated by generate-all-modules. DO NOT EDIT.

package aerospike

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for aerospike containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("3000"),
		ctropts.WithWaitForLog("service ready", 30*time.Second),
	)
}
