// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package aerospike provides testctr support for aerospike containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: aerospike:ce-6.4.0.1
  - Port: 3000
  - Wait Strategy: "service ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/aerospike"
	)

	func TestWithAerospike(t *testing.T) {
		container := testctr.New(t, "aerospike:ce-6.4.0.1", aerospike.Default())
		// Use container...
	}


*/
package aerospike
