// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package neo4j provides testctr support for neo4j containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: neo4j:5
  - Port: 7687
  - Wait Strategy: "Started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/neo4j"
	)

	func TestWithNeo4j(t *testing.T) {
		container := testctr.New(t, "neo4j:5", neo4j.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

*/
package neo4j
