// Code generated by generate-all-modules. DO NOT EDIT.

package neo4j

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for neo4j containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("7687"),
		ctropts.WithWaitForLog("Started", 30*time.Second),
		// TODO: Add DSN provider when fully implemented
	)
}
