// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package redpanda provides testctr support for redpanda containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: redpandadata/redpanda:v23.2.3
  - Port: 9092
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/redpanda"
	)

	func TestWithRedpanda(t *testing.T) {
		container := testctr.New(t, "redpandadata/redpanda:v23.2.3", redpanda.Default())
		// Use container...
	}


*/
package redpanda
