// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package openfga provides testctr support for openfga containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: openfga/openfga:v1.3.0
  - Port: 8080
  - Wait Strategy: "OpenFGA server starting"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/openfga"
	)

	func TestWithOpenfga(t *testing.T) {
		container := testctr.New(t, "openfga/openfga:v1.3.0", openfga.Default())
		// Use container...
	}


*/
package openfga
