// Code generated by generate-all-modules. DO NOT EDIT.

package openfga

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for openfga containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8080"),
		ctropts.WithWaitForLog("OpenFGA server starting", 30*time.Second),
	)
}
