// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package rabbitmq provides testctr support for rabbitmq containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: rabbitmq:3-management
  - Port: 5672
  - Wait Strategy: "Server startup complete"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/rabbitmq"
	)

	func TestWithRabbitmq(t *testing.T) {
		container := testctr.New(t, "rabbitmq:3-management", rabbitmq.Default())
		// Use container...
	}


*/
package rabbitmq
