// Code generated by generate-all-modules. DO NOT EDIT.

package rabbitmq

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for rabbitmq containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("5672"),
		ctropts.WithWaitForLog("Server startup complete", 30*time.Second),
	)
}
