// Code generated by generate-all-modules. DO NOT EDIT.

package couchbase

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for couchbase containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8091"),
		ctropts.WithWaitForLog("Couchbase Server has started", 30*time.Second),
	)
}
