// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package couchbase provides testctr support for couchbase containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: couchbase:7
  - Port: 8091
  - Wait Strategy: "Couchbase Server has started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/couchbase"
	)

	func TestWithCouchbase(t *testing.T) {
		container := testctr.New(t, "couchbase:7", couchbase.Default())
		// Use container...
	}


*/
package couchbase
