// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package pinecone provides testctr support for pinecone containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: pinecone:latest
  - Port: 8080
  - Wait Strategy: "ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/pinecone"
	)

	func TestWithPinecone(t *testing.T) {
		container := testctr.New(t, "pinecone:latest", pinecone.Default())
		// Use container...
	}


*/
package pinecone
