// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package yugabytedb provides testctr support for yugabytedb containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: yugabytedb/yugabyte:2.18.0.0-b80
  - Port: 5433
  - Wait Strategy: "Started YugabyteDB"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/yugabytedb"
	)

	func TestWithYugabytedb(t *testing.T) {
		container := testctr.New(t, "yugabytedb/yugabyte:2.18.0.0-b80", yugabytedb.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

*/
package yugabytedb
