// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package minio provides testctr support for minio containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: minio/minio:latest
  - Port: 9000
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/minio"
	)

	func TestWithMinio(t *testing.T) {
		container := testctr.New(t, "minio/minio:latest", minio.Default())
		// Use container...
	}


*/
package minio
