// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package artemis provides testctr support for artemis containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: artemis:latest
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/artemis"
	)

	func TestWithArtemis(t *testing.T) {
		container := testctr.New(t, "artemis:latest", artemis.Default())
		// Use container...
	}


*/
package artemis
