// Code generated by parse-tc-module. DO NOT EDIT.

package mysql_test

import (
	"testing"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/exp/gen/modules/mysql"
)

func TestMysqlContainer(t *testing.T) {
	t.Parallel()

	container := testctr.New(t, "mysql:8.0.36", mysql.Default())
	
	if container.ID() == "" {
		t.Fatal("container ID should not be empty")
	}

	port := container.Port("3306")
	if port == "" {
		t.Fatal("container port should not be empty")
	}

	endpoint := container.Endpoint("3306")
	if endpoint == "" {
		t.Fatalf("failed to get endpoint for port 3306")
	}
}

func TestMysqlWithOptions(t *testing.T) {
	t.Parallel()

	container := testctr.New(t, "mysql:8.0.36",
		mysql.Default(),
		// Add custom options here
	)

	if container.ID() == "" {
		t.Fatal("container ID should not be empty")
	}
}
