// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package localstack provides testctr support for localstack containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: localstack/localstack:3.0
  - Port: 4566
  - Wait Strategy: "Ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/localstack"
	)

	func TestWithLocalstack(t *testing.T) {
		container := testctr.New(t, "localstack/localstack:3.0", localstack.Default())
		// Use container...
	}


*/
package localstack
