// Code generated by generate-all-modules. DO NOT EDIT.

package localstack

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for localstack containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("4566"),
		ctropts.WithWaitForLog("Ready", 30*time.Second),
	)
}
