#!/bin/bash
export PATH=$(pwd):.tools:$PATH

# plan
# ./make-safe-progress.sh
# attach-sandbox-content
docker logs $(get-latest-sandbox)
(echo "we will fix what went wrong"; ctx-exec docker logs $(get-latest-sandbox) ; ctx-exec git st .; ~/code-to-gpt.sh) | cgpt -s "we are fixing issues in this codebase. output an invocation of ./make-fix-suggestion.sh; at the top of teh bash script, output comments explaining <antthinking thoughts" -p "./make-fix-suggestion.sh" | tee mkfix.sh
git add mkfix.sh
git commit -m "git-notes: Adding suggestions to fix the codebase"
sandbox-exec ./mkfix.sh
git add fixes.sh
git commit -m "git-notes: Adding suggestions to fix the codebase"
sandbox-exec ./fixes.sh
# (ctx-exec git show --notes='*'; ctx-exec git st .; ~/code-to-gpt.sh) | cgpt -s $(cat .claude-system-prompt-analyze-attempt) |tee /tmp/claude-analysis; cat /tmp/claude-analysis |git notes --ref attempt-analysis add -F-
# (ctx-exec git show --notes='*'; ctx-exec git st .; ~/code-to-gpt.sh) | cgpt -s $(cat .claude-system-prompt-analyze-attempt) |tee /tmp/claude-analysis; cat /tmp/claude-analysis |git notes --ref attempt-analysis add -F-
# sh eval-make-safe-progress.sh | tee /tmp/eval-make-safe-progress; cat /tmp/eval-make-safe-progress |git notes --ref eval-safe-progress add -F- ;
