.PHONY: test install

test:
	@echo "Running tests..."
	@bash test-git-goals.sh

install:
	@echo "Installing git-goals..."
	@cp git-goals* /usr/local/bin/

clean:
	@echo "Cleaning up..."
	@rm -f *.log
