// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package cassandra provides testctr support for cassandra containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: cassandra:4
  - Port: 9042
  - Wait Strategy: "Created default superuser role"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/cassandra"
	)

	func TestWithCassandra(t *testing.T) {
		container := testctr.New(t, "cassandra:4", cassandra.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

*/
package cassandra
