// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package meilisearch provides testctr support for meilisearch containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: getmeili/meilisearch:v1.3
  - Port: 7700
  - Wait Strategy: "Meilisearch is ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/meilisearch"
	)

	func TestWithMeilisearch(t *testing.T) {
		container := testctr.New(t, "getmeili/meilisearch:v1.3", meilisearch.Default())
		// Use container...
	}


*/
package meilisearch
