// Code generated by generate-all-modules. DO NOT EDIT.

package meilisearch

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for meilisearch containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("7700"),
		ctropts.WithWaitForLog("Meilisearch is ready", 30*time.Second),
	)
}
