// Code generated by generate-all-modules. DO NOT EDIT.

package redis

import (
	"fmt"
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for redis containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("6379/tcp"),
		ctropts.WithWaitForLog("Ready to accept connections", 30*time.Second),
	)
}

// WithTLS WithTLS sets the TLS configuration for the redis container, setting the 6380/tcp port to listen on for TLS connections and using a secure URL (rediss://).
func WithTLS(value string) testctr.Option {
	return testctr.WithEnv("REDIS_TLS", value)
}

// WithConfigFile WithConfigFile sets the config file to be used for the redis container, and sets the command to run the redis server using the passed config file
func WithConfigFile(value string) testctr.Option {
	return testctr.WithEnv("REDIS_CONFIGFILE", value)
}

// WithLogLevel WithLogLevel sets the log level for the redis server process See "[RedisModule_Log]" for more information. [RedisModule_Log]: https://redis.io/docs/reference/modules/modules-api-ref/#redismodule_log
func WithLogLevel(value LogLevel) testctr.Option {
	return testctr.WithEnv("REDIS_LOGLEVEL", fmt.Sprintf("%v", value))
}

// WithSnapshotting WithSnapshotting sets the snapshotting configuration for the redis server process. You can configure Redis to have it save the dataset every N seconds if there are at least M changes in the dataset. This method allows Redis to benefit from copy-on-write semantics. See [Snapshotting] for more information. [Snapshotting]: https://redis.io/docs/management/persistence/#snapshotting
func WithSnapshotting(value int) testctr.Option {
	return testctr.WithEnv("REDIS_SNAPSHOTTING", fmt.Sprintf("%v", value))
}
