package webidl2plan9

import (
	"fmt"
	"strings"
)

// Design is the filesystem interpretation the renderer derives from an IDL.
type Design struct {
	Root     string // service root, e.g. "/llm"
	APIName  string
	Shape    string // classified shape
	ShapeWhy string
	Primary  *Interface // the durable-handle interface, for instance-connection shapes
	idl      *IDL
}

// nonCrossable are Web IDL types whose values cannot cross a 9P file boundary
// and must therefore fail closed (or be represented as staged bytes). This is
// the one piece of fails-closed judgment the renderer encodes; it is derived
// from the type, not invented.
var nonCrossable = map[string]bool{
	"object":       true, // opaque JS object / function identity
	"EventHandler": true,
	"AbortSignal":  true, // a host control object; mapped to a ctl verb, not a file value
}

// Classify picks the namespace shape from the IDL alone, by documented
// heuristic (the IDL does not state the shape; this is the renderer's judgment,
// surfaced in the manpage so a reviewer can check it):
//   - instance-connection: some static method returns Promise<ThisInterface> (a
//     durable handle the caller mints and reuses) — e.g. create()->LanguageModel.
//   - resource-tree: multiple peer interfaces with no minted handle.
//   - request-response: only static one-shot methods, no returned interface.
func (idl *IDL) Classify() (shape, why string, primary *Interface) {
	for _, iface := range idl.Interfaces {
		for _, op := range iface.Operations {
			if op.Static && returnsInterface(op.Return, iface.Name) {
				return "instance-connection",
					fmt.Sprintf("%s.%s() returns Promise<%s>, a durable handle the caller mints and reuses across calls", iface.Name, op.Name, iface.Name),
					iface
			}
		}
	}
	// any non-static methods on a single interface => that interface is the resource
	for _, iface := range idl.Interfaces {
		if hasInstanceMethods(iface) {
			return "resource-tree",
				fmt.Sprintf("%s exposes instance methods but no minted handle; modeled as an addressable resource", iface.Name),
				iface
		}
	}
	return "request-response", "only one-shot static operations; no durable handle returned", nil
}

func returnsInterface(ret, name string) bool {
	// Promise<Name> or Promise<Name?>
	r := strings.TrimSpace(ret)
	r = strings.TrimPrefix(r, "Promise<")
	r = strings.TrimSuffix(r, ">")
	r = strings.TrimSuffix(r, "?")
	return r == name
}

func hasInstanceMethods(iface *Interface) bool {
	for _, op := range iface.Operations {
		if !op.Static {
			return true
		}
	}
	return len(iface.Attributes) > 0
}

// Render produces the service(4) manpage. apiName and root are caller-supplied
// (the IDL does not name the service); everything else is derived.
func Render(idl *IDL, apiName, root string) string {
	shape, why, primary := idl.Classify()
	d := &Design{Root: root, APIName: apiName, Shape: shape, ShapeWhy: why, Primary: primary, idl: idl}
	var b strings.Builder
	d.header(&b)
	d.tree(&b)
	d.perFile(&b)
	d.mappingTable(&b)
	d.boundary(&b)
	d.caveats(&b)
	return b.String()
}

func (d *Design) header(b *strings.Builder) {
	fmt.Fprintf(b, "# %s(4) — A Plan 9 / Wanix Synthetic Filesystem for %s\n\n", strings.TrimPrefix(d.Root, "/"), d.APIName)
	fmt.Fprintf(b, "<!-- generated by webidl2plan9 from Web IDL; shape and fails-closed policy are derived heuristics, marked inline. Verify against the source. -->\n\n")
	fmt.Fprintf(b, "## TL;DR\n\n")
	fmt.Fprintf(b, "- Shape: **%s** — %s.\n", d.Shape, d.ShapeWhy)
	switch d.Shape {
	case "instance-connection":
		fmt.Fprintf(b, "- `%s/clone` allocates a session `$id/`; static methods map to root files, instance members to `$id/` files.\n", d.Root)
	case "resource-tree":
		fmt.Fprintf(b, "- Each interface is an addressable resource directory; operations on it are one-shot `req`/`resp` files.\n")
	case "request-response":
		fmt.Fprintf(b, "- No durable handle: each operation is a one-shot `req`/`resp` pair under its own directory.\n")
	}
	fmt.Fprintf(b, "\n")
}

func (d *Design) tree(b *strings.Builder) {
	fmt.Fprintf(b, "## Filesystem tree\n\n```text\n%s/\n", d.Root)
	if d.Shape == "instance-connection" && d.Primary != nil {
		fmt.Fprintf(b, "├── clone%s← read to allocate a session $id\n", pad("clone"))
		// static (service-wide) methods/attrs of the primary interface
		for _, op := range d.Primary.Operations {
			if op.Static && !returnsInterface(op.Return, d.Primary.Name) {
				name := op.Name
				fmt.Fprintf(b, "├── %s%s← %s (static %s)\n", name, pad(name), roleOf(op), op.Return)
			}
		}
		fmt.Fprintf(b, "└── $id/%s(one durable %s)\n", pad("$id/"), d.Primary.Name)
		// instance attributes -> status/value files
		for _, a := range d.Primary.Attributes {
			if a.Deprecated {
				continue
			}
			fmt.Fprintf(b, "    ├── %s%s← read-only: %s\n", a.Name, pad("    "+a.Name), a.Type)
		}
		// instance methods -> ctl verbs or sub-allocators
		fmt.Fprintf(b, "    ├── ctl%s← write: %s\n", pad("    ctl"), strings.Join(d.ctlVerbs(), ", "))
		fmt.Fprintf(b, "    └── status%s← read-only: session state\n", pad("    status"))
	} else {
		for _, iface := range d.idl.Interfaces {
			fmt.Fprintf(b, "├── %s/%s(resource: %s)\n", lower(iface.Name), pad(lower(iface.Name)+"/"), iface.Name)
		}
	}
	fmt.Fprintf(b, "```\n\n")
}

func (d *Design) ctlVerbs() []string {
	var verbs []string
	if d.Primary != nil {
		for _, op := range d.Primary.Operations {
			if op.Static {
				continue
			}
			verbs = append(verbs, op.Name)
		}
	}
	// destroy comes from a DestroyableModel-style mixin
	for _, mixins := range d.idl.Includes {
		for _, mx := range mixins {
			if strings.Contains(strings.ToLower(mx), "destroy") {
				verbs = append(verbs, "destroy")
			}
		}
	}
	if len(verbs) == 0 {
		verbs = []string{"(none)"}
	}
	return verbs
}

// roleOf maps an operation to its file role by return type — the deterministic
// part the it8 design got wrong by hand.
func roleOf(op *Operation) string {
	ret := strings.TrimSpace(op.Return)
	switch {
	case strings.HasPrefix(ret, "Promise<") && returnsInterfaceAny(ret):
		return "allocate/clone a handle"
	case ret == "ReadableStream":
		return "incremental stream output"
	case strings.Contains(ret, "double") || strings.Contains(ret, "long") || strings.Contains(ret, "float"):
		return "read: numeric value (" + ret + ")"
	case strings.Contains(ret, "DOMString"):
		return "read: text result"
	case strings.Contains(ret, "undefined"):
		return "ctl verb (no return value)"
	default:
		return "read: " + ret
	}
}

func returnsInterfaceAny(ret string) bool {
	r := strings.TrimPrefix(strings.TrimSpace(ret), "Promise<")
	r = strings.TrimSuffix(strings.TrimSuffix(r, ">"), "?")
	// crude: capitalized, not a known scalar/string
	return r != "" && r[0] >= 'A' && r[0] <= 'Z' &&
		!strings.Contains(r, "DOMString") && !strings.Contains(r, "double") &&
		!strings.Contains(r, "Availability")
}

func (d *Design) perFile(b *strings.Builder) {
	fmt.Fprintf(b, "## Per-file semantics\n\n")
	if d.Primary == nil {
		fmt.Fprintf(b, "_(resource-tree per-file semantics omitted in prototype)_\n\n")
		return
	}
	for _, a := range d.Primary.Attributes {
		dep := ""
		if a.Deprecated {
			dep = " **(deprecated — fails closed / symlink to current name)**"
		}
		fmt.Fprintf(b, "- `%s/$id/%s` — read-only, returns `%s` (`%s` attribute)%s.\n", d.Root, a.Name, a.Type, d.Primary.Name, dep)
	}
	fmt.Fprintf(b, "\n### `%s/$id/ctl` verbs\n\n| verb | from | return type | role |\n|---|---|---|---|\n", d.Root)
	for _, op := range d.Primary.Operations {
		if op.Static {
			continue
		}
		fmt.Fprintf(b, "| `%s` | `%s.%s()` | `%s` | %s |\n", op.Name, d.Primary.Name, op.Name, op.Return, roleOf(op))
	}
	fmt.Fprintf(b, "\n")
}

func (d *Design) mappingTable(b *strings.Builder) {
	fmt.Fprintf(b, "## Feature mapping\n\nEvery IDL surface, derived mechanically (this is the table that drifts when written by hand).\n\n")
	fmt.Fprintf(b, "| IDL surface | kind | path | role / return |\n|---|---|---|---|\n")
	for _, iface := range d.idl.Interfaces {
		for _, op := range iface.Operations {
			path := d.opPath(iface, op)
			fmt.Fprintf(b, "| `%s.%s()` | operation | `%s` | %s |\n", iface.Name, op.Name, path, roleOf(op))
		}
		for _, a := range iface.Attributes {
			fmt.Fprintf(b, "| `%s.%s` | attribute | `%s/$id/%s` | read: %s |\n", iface.Name, a.Name, d.Root, a.Name, a.Type)
		}
	}
	for _, dict := range d.idl.Dictionaries {
		for _, m := range dict.Members {
			fmt.Fprintf(b, "| `%s.%s` | dict member | staged draft file | write: %s%s |\n", dict.Name, m.Name, typeNote(m.Type), reqNote(m.Required))
		}
	}
	for _, cb := range d.idl.Callbacks {
		fmt.Fprintf(b, "| `%s` | callback | `call`/`return` pipe pair | async RPC |\n", cb.Name)
	}
	fmt.Fprintf(b, "\n")
}

func (d *Design) opPath(iface *Interface, op *Operation) string {
	if op.Static && returnsInterface(op.Return, iface.Name) {
		return d.Root + "/clone"
	}
	if op.Static {
		return d.Root + "/" + op.Name
	}
	return d.Root + "/$id/ctl ← " + op.Name
}

func (d *Design) boundary(b *strings.Builder) {
	fmt.Fprintf(b, "## Supported / fails-closed boundary\n\n**Fails closed** (types that cannot cross a file boundary, derived from the IDL):\n\n")
	seen := map[string]bool{}
	for _, dict := range d.idl.Dictionaries {
		for _, m := range dict.Members {
			base := strings.TrimSuffix(m.Type, "?")
			if nonCrossable[base] && !seen[base] {
				fmt.Fprintf(b, "- `%s` (in `%s.%s`) — opaque host value; no file representation.\n", base, dict.Name, m.Name)
				seen[base] = true
			}
		}
	}
	for _, iface := range d.idl.Interfaces {
		for _, a := range iface.Attributes {
			if nonCrossable[a.Type] && !seen[a.Type] {
				fmt.Fprintf(b, "- `%s` (in `%s.%s`) — event handler; surfaced as a blocking `event` file instead.\n", a.Type, iface.Name, a.Name)
				seen[a.Type] = true
			}
		}
	}
	// union-typed values: note which members are byte-crossable vs not
	for _, td := range d.idl.Typedefs {
		if len(td.Union) > 0 {
			fmt.Fprintf(b, "- union `%s` = %s — crossable members become staged byte slots; host-object members fail closed.\n", td.Name, strings.Join(td.Union, " | "))
		}
	}
	fmt.Fprintf(b, "\n")
}

func (d *Design) caveats(b *strings.Builder) {
	fmt.Fprintf(b, "## Caveats\n\n")
	fmt.Fprintf(b, "- **Shape and fails-closed policy are heuristics**, not from the IDL — verify the shape (%s) against the API's actual lifecycle.\n", d.Shape)
	fmt.Fprintf(b, "- Worked `rc` examples and prose rationale are NOT generated here; this tool emits the deterministic skeleton an author or LLM then completes.\n")
	fmt.Fprintf(b, "- Deprecated/experimental members are flagged from IDL comments; decide per-member whether to fail closed or symlink.\n")
}

// --- formatting helpers ---

func lower(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func typeNote(t string) string { return t }

func reqNote(req bool) string {
	if req {
		return " (required)"
	}
	return ""
}

// pad returns alignment spaces for the tree comment column.
func pad(s string) string {
	const col = 36
	n := col - len(s)
	if n < 1 {
		n = 1
	}
	return strings.Repeat(" ", n)
}
