// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package qdrant provides testctr support for qdrant containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: qdrant/qdrant:latest
  - Port: 6333
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/qdrant"
	)

	func TestWithQdrant(t *testing.T) {
		container := testctr.New(t, "qdrant/qdrant:latest", qdrant.Default())
		// Use container...
	}


*/
package qdrant
