// Code generated by generate-all-modules. DO NOT EDIT.

package arangodb

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for arangodb containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8529"),
		ctropts.WithWaitForLog("ArangoDB is ready for business", 30*time.Second),
		// TODO: Add DSN provider when fully implemented
	)
}
