// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package arangodb provides testctr support for arangodb containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: arangodb:3.11
  - Port: 8529
  - Wait Strategy: "ArangoDB is ready for business"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/arangodb"
	)

	func TestWithArangodb(t *testing.T) {
		container := testctr.New(t, "arangodb:3.11", arangodb.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

*/
package arangodb
