// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package dynamodb provides testctr support for dynamodb containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: amazon/dynamodb-local:latest
  - Port: 8000
  - Wait Strategy: "Started DynamoDB Local"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/dynamodb"
	)

	func TestWithDynamodb(t *testing.T) {
		container := testctr.New(t, "amazon/dynamodb-local:latest", dynamodb.Default())
		// Use container...
	}


*/
package dynamodb
