// Code generated by generate-all-modules. DO NOT EDIT.

package dynamodb

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for dynamodb containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8000"),
		ctropts.WithWaitForLog("Started DynamoDB Local", 30*time.Second),
	)
}
