// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package toxiproxy provides testctr support for toxiproxy containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: ghcr.io/shopify/toxiproxy:2.5.0
  - Port: 8474
  - Wait Strategy: "toxiproxy started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/toxiproxy"
	)

	func TestWithToxiproxy(t *testing.T) {
		container := testctr.New(t, "ghcr.io/shopify/toxiproxy:2.5.0", toxiproxy.Default())
		// Use container...
	}


*/
package toxiproxy
