// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package socat provides testctr support for socat containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: alpine/socat:latest
  - Port: 8080
  - Wait Strategy: "ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/socat"
	)

	func TestWithSocat(t *testing.T) {
		container := testctr.New(t, "alpine/socat:latest", socat.Default())
		// Use container...
	}


*/
package socat
