// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package valkey provides testctr support for valkey containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: valkey/valkey:7.2
  - Port: 6379
  - Wait Strategy: "Ready to accept connections"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/valkey"
	)

	func TestWithValkey(t *testing.T) {
		container := testctr.New(t, "valkey/valkey:7.2", valkey.Default())
		// Use container...
	}


*/
package valkey
