// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package mockserver provides testctr support for mockserver containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: mockserver/mockserver:5.15.0
  - Port: 1080
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/mockserver"
	)

	func TestWithMockserver(t *testing.T) {
		container := testctr.New(t, "mockserver/mockserver:5.15.0", mockserver.Default())
		// Use container...
	}


*/
package mockserver
