// Code generated by generate-all-modules. DO NOT EDIT.

package mockserver

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for mockserver containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("1080"),
		ctropts.WithWaitForLog("started", 30*time.Second),
	)
}
