// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package opensearch provides testctr support for opensearch containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: opensearchproject/opensearch:2
  - Port: 9200/tcp
  - Wait Strategy: "started"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/opensearch"
	)

	func TestWithOpensearch(t *testing.T) {
		container := testctr.New(t, "opensearchproject/opensearch:2", opensearch.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

# Configuration Options

  - WithPassword: WithPassword sets the password for the OpenSearch container.
  - WithUsername: WithUsername sets the username for the OpenSearch container.
*/
package opensearch
