// Code generated by generate-all-modules. DO NOT EDIT.

package azurite

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for azurite containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("10000"),
		ctropts.WithWaitForLog("Azurite Blob service is successfully listening", 30*time.Second),
	)
}
