// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package azurite provides testctr support for azurite containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: mcr.microsoft.com/azure-storage/azurite:latest
  - Port: 10000
  - Wait Strategy: "Azurite Blob service is successfully listening"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/azurite"
	)

	func TestWithAzurite(t *testing.T) {
		container := testctr.New(t, "mcr.microsoft.com/azure-storage/azurite:latest", azurite.Default())
		// Use container...
	}


*/
package azurite
