// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package inbucket provides testctr support for inbucket containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: inbucket/inbucket:latest
  - Port: 9000
  - Wait Strategy: "Inbucket is ready"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/inbucket"
	)

	func TestWithInbucket(t *testing.T) {
		container := testctr.New(t, "inbucket/inbucket:latest", inbucket.Default())
		// Use container...
	}


*/
package inbucket
