// Code generated by generate-all-modules. DO NOT EDIT.

package inbucket

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for inbucket containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("9000"),
		ctropts.WithWaitForLog("Inbucket is ready", 30*time.Second),
	)
}
