// Code generated by generate-all-modules. DO NOT EDIT.

package consul

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for consul containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8500"),
		ctropts.WithWaitForLog("Consul agent running", 30*time.Second),
	)
}
