// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package consul provides testctr support for consul containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: hashicorp/consul:1.15
  - Port: 8500
  - Wait Strategy: "Consul agent running"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/consul"
	)

	func TestWithConsul(t *testing.T) {
		container := testctr.New(t, "hashicorp/consul:1.15", consul.Default())
		// Use container...
	}


*/
package consul
