// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package vault provides testctr support for vault containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: hashicorp/vault:1.15
  - Port: 8200
  - Wait Strategy: "Root Token:"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/vault"
	)

	func TestWithVault(t *testing.T) {
		container := testctr.New(t, "hashicorp/vault:1.15", vault.Default())
		// Use container...
	}


*/
package vault
