// Code generated by generate-all-modules. DO NOT EDIT.

package vault

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for vault containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("8200"),
		ctropts.WithWaitForLog("Root Token:", 30*time.Second),
	)
}
