// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package postgres provides testctr support for postgres containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: postgres:15
  - Port: 5432
  - Wait Strategy: "database system is ready to accept connections"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/postgres"
	)

	func TestWithPostgres(t *testing.T) {
		container := testctr.New(t, "postgres:15", postgres.Default())
		// Use container...
	}

# DSN Support

This module includes DSN (Data Source Name) support for easy database connections.
Full DSN provider implementation is pending.

# Configuration Options

  - WithSQLDriver: WithSQLDriver sets the SQL driver to use for the container. It is passed to sql.Open() to connect to the database when making or restoring snapshots. This can be set if your app imports a different postgres driver, f.ex. "pgx"
  - WithConfigFile: WithConfigFile sets the config file to be used for the postgres container It will also set the "config_file" parameter to the path of the config file as a command line argument to the container
  - WithDatabase: WithDatabase sets the initial database to be created when the container starts It can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of WithUser will be used.
  - WithInitScripts: WithInitScripts sets the init scripts to be run when the container starts. These init scripts will be executed in sorted name order as defined by the container's current locale, which defaults to en_US.utf8. If you need to run your scripts in a specific order, consider using `WithOrderedInitScripts` instead.
  - WithOrderedInitScripts: WithOrderedInitScripts sets the init scripts to be run when the container starts. The scripts will be run in the order that they are provided in this function.
  - WithPassword: WithPassword sets the initial password of the user to be created when the container starts It is required for you to use the PostgreSQL image. It must not be empty or undefined. This environment variable sets the superuser password for PostgreSQL.
  - WithUsername: WithUsername sets the initial username to be created when the container starts It is used in conjunction with WithPassword to set a user and its password. It will create the specified user with superuser power and a database with the same name. If it is not specified, then the default user of postgres will be used.
  - WithSnapshotName: WithSnapshotName adds a specific name to the snapshot database created from the main database defined on the container. The snapshot must not have the same name as your main database, otherwise it will be overwritten
  - WithSSLCert: WithSSLSettings configures the Postgres server to run with the provided CA Chain This will not function if the corresponding postgres conf is not correctly configured. Namely the paths below must match what is set in the conf file
*/
package postgres
