// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package k3s provides testctr support for k3s containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: rancher/k3s:v1.27.3-k3s1
  - Port: 6443
  - Wait Strategy: "k3s is up and running"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/k3s"
	)

	func TestWithK3s(t *testing.T) {
		container := testctr.New(t, "rancher/k3s:v1.27.3-k3s1", k3s.Default())
		// Use container...
	}


*/
package k3s
