// Code generated by generate-all-modules. DO NOT EDIT.

package k3s

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for k3s containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("6443"),
		ctropts.WithWaitForLog("k3s is up and running", 30*time.Second),
	)
}
