// Code generated by generate-all-modules. DO NOT EDIT.

package dind

import (
	"time"

	"github.com/tmc/misc/testctr"
	"github.com/tmc/misc/testctr/ctropts"
)

// Default returns the default configuration for dind containers.
func Default() testctr.Option {
	return testctr.Options(
		testctr.WithPort("2376"),
		ctropts.WithWaitForLog("API listen on", 30*time.Second),
	)
}
