// Code generated by generate-all-modules. DO NOT EDIT.

/*
Package dind provides testctr support for dind containers.

This package was auto-generated from the testcontainers-go project.

# Default Configuration

The default configuration uses:
  - Image: docker:dind
  - Port: 2376
  - Wait Strategy: "API listen on"

# Usage

	import (
		"testing"
		"github.com/tmc/misc/testctr"
		"github.com/tmc/misc/testctr/exp/modules/dind"
	)

	func TestWithDind(t *testing.T) {
		container := testctr.New(t, "docker:dind", dind.Default())
		// Use container...
	}


*/
package dind
